### ISSUE TITLE
cannot run the code locally

### ISSUE THREAD

**Issue by alexhmyang** [fireactjs/saas#35]
![image](https://user-images.githubusercontent.com/10215059/226098757-8aeb1139-0b17-4136-a376-b57a0bde476d.png)
![image](https://user-images.githubusercontent.com/10215059/226098764-4400427e-6e0c-4601-bf96-93cc9f77b71a.png)
![image](https://user-images.githubusercontent.com/10215059/226098773-ca80f99d-9411-4a75-9c74-8c931b775490.png)

> WARNING in ./node_modules/@firebase/webchannel-wrapper/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\proj2022\chatgpt_toB\saas\node_modules\@firebase\webchannel-wrapper\dist\src\com\google\javascript\jscomp\js\util\owns.js' file: Error: ENOENT: no such file or directory, open 'F:\proj2022\chatgpt_toB\saas\node_modules\@firebase\webchannel-wrapper\dist\src\com\google\javascript\jscomp\js\util\owns.js'

WARNING in ./node_modules/@firebase/webchannel-wrapper/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'F:\proj2022\chatgpt_toB\saas\node_modules\@firebase\webchannel-wrapper\dist\src\com\google\javascript\jscomp\js\util\polyfill.js' file: Error: ENOENT: no such file or directory, open 'F:\proj2022\chatgpt_toB\saas\node_modules\@firebase\webchannel-wrapper\dist\src\com\google\javascript\jscomp\js\util\polyfill.js'

**Comment by chaoming** [comment]
Please give some details on how you installed the package.

**Comment by alexhmyang** [comment]
> 

1 git clone https://github.com/fireactjs/saas.git
2 npm install 
3 npm run start

**Comment by chaoming** [comment]
Please read the README of the repo or the installation documentation here: https://fireactjs.com/docs/saas-package/installation/
