### ISSUE TITLE
createSubscription error

### ISSUE THREAD

**Issue by SArchS** [fireactjs/saas#38]
https://REDACTED.cloudfunctions.net/fireactjsSaas-createSubscription
gives " 500 Internal Server Error"

Since I followed the tutorial to the tea, I assume the problem is with the functions package? Any idea what's wrong?

**Comment by chaoming** [comment]
Please check the could function log in your GCP for the function `fireactjsSaas-createSubscription` for more detailed error information.

**Comment by SArchS** [comment]
{
  "textPayload": "Unhandled error FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.\n    at FirebaseAppError.FirebaseError [as constructor] (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/utils/error.js:44:28)\n    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/utils/error.js:90:28)\n    at new FirebaseAppError (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/utils/error.js:125:28)\n    at AppStore.getApp (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/app/lifecycle.js:67:19)\n    at FirebaseNamespaceInternals.app (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/app/firebase-namespace.js:54:33)\n    at FirebaseNamespace.app (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/app/firebase-namespace.js:321:30)\n    at FirebaseNamespace.ensureApp (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/app/firebase-namespace.js:335:24)\n    at FirebaseNamespace.fn (/workspace/node_modules/@fireactjs/saas-cloud-functions/node_modules/firebase-admin/lib/app/firebase-namespace.js:163:30)\n    at getDoc (/workspace/node_modules/@fireactjs/saas-cloud-functions/lib/index.js:12:30)\n    at getStripeCustomerId (/workspace/node_modules/@fireactjs/saas-cloud-functions/lib/index.js:34:16) {\n  errorInfo: {\n    code: 'app/no-app',\n    message: 'The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'\n  },\n  codePrefix: 'app'\n}",
  "insertId": "64680838000ce30129d11787",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "function_name": "fireactjsSaas-createSubscription",
      "region": "us-central1",
      "project_id": "fkss-a17ba"
    }
  },
  "timestamp": "2023-05-19T23:37:28.844545Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "dnhmts8n0g2x",
    "instance_id": "00c61b117cba20d2973a519f49d02ad009c63f5fb376ff8938655a6576000be1c625f21d9849ccab63a1aee33acc141064be28bbc7e8c1ee77c0"
  },
  "logName": "projects/fkss-a17ba/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/fkss-a17ba/traces/7460473e9051d08361e5112c671e628c",
  "receiveTimestamp": "2023-05-19T23:37:29.050739252Z"
}

**Comment by SArchS** [comment]
The thing is the initialization takes place just as in the docs
const admin = require("firebase-admin");
admin.initializeApp();
const config = require("./config.json");
let fireactjsSaasFunctions = require("@fireactjs/saas-cloud-functions")(config);
exports.fireactjsSaas = fireactjsSaasFunctions;

**Comment by chaoming** [comment]
Could you share your `functions` folder structure?

Based on the error message, it seems the `functions\index.js` is not used if you have the above code in the file. When initialising Firebase, it could create different namespaces and maybe the `index.js` is in a different namespace.

**Comment by SArchS** [comment]
@chaoming added you to the repo

**Comment by SArchS** [comment]
![image](https://github.com/fireactjs/saas/assets/118494586/9ad31173-adfb-4f9b-8f4a-4ad86947d568)

**Comment by SArchS** [comment]
[SOLVED] changed the code to 
`const admin = require("firebase-admin");
admin.initializeApp();
const config = require("./config.json");

let fireactjsSaasFunctions = require("./lib")(config);

exports.fireactjsSaas = fireactjsSaasFunctions;
` and copied the /lib from your example repo and everything works now

**Comment by chaoming** [comment]
That's strange. So the npm package `@fireactjs/saas-cloud-functions` doesn't work for you?

**Comment by SArchS** [comment]
Exactly, for some reason it appears to be a conflict regarding the  admin.initializeApp(); in the package
