### ISSUE TITLE
I get this when 'npm i @fireactjs/saas-cloud-functions'

### ISSUE THREAD

**Issue by jmg22** [fireactjs/saas#44]
npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit No fix available for react-scripts@>=2.1.4
npm WARN audit Updating @fireactjs/saas to 1.2.0, which is a SemVer major change.
npm WARN audit No fix available for @fireactjs/core@*
npm WARN audit No fix available for @fireactjs/saas-cloud-functions@*

removed 4 packages, changed 1 package, and audited 1836 packages in 7s

# npm audit report

degenerator  <3.0.1
Severity: high
Code Injection in pac-resolver - https://github.com/advisories/GHSA-9j49-mfvp-vmhm
No fix available
node_modules/degenerator
  pac-resolver  <=4.2.0
  Depends on vulnerable versions of degenerator
  Depends on vulnerable versions of netmask
  node_modules/pac-resolver
    pac-proxy-agent  <=4.1.0
    Depends on vulnerable versions of pac-resolver
    node_modules/pac-proxy-agent
      proxy-agent  1.1.0 - 4.0.1
      Depends on vulnerable versions of pac-proxy-agent
      node_modules/proxy-agent
        mailgun-js  >=0.6.8
        Depends on vulnerable versions of proxy-agent
        node_modules/mailgun-js
          @fireactjs/saas-cloud-functions  *
          Depends on vulnerable versions of mailgun-js
          node_modules/@fireactjs/saas-cloud-functions

netmask  <=2.0.0
Severity: critical
Improper parsing of octal bytes in netmask - https://github.com/advisories/GHSA-4c7m-wxvm-r7gc
netmask npm package mishandles octal input data - https://github.com/advisories/GHSA-pch5-whg9-qr2r
No fix available
node_modules/netmask

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
No fix available
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          Depends on vulnerable versions of resolve-url-loader
          node_modules/react-scripts
            @fireactjs/core  *
            Depends on vulnerable versions of react-scripts
            node_modules/@fireactjs/core
            @fireactjs/saas  *
            Depends on vulnerable versions of @fireactjs/core
            Depends on vulnerable versions of react-scripts
            node_modules/@fireactjs/saas

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
No fix available
node_modules/resolve-url-loader/node_modules/postcss
  resolve-url-loader  0.0.1-experiment-postcss || 3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader

17 vulnerabilities (4 moderate, 12 high, 1 critical)

Some issues need review, and may require choosing
a different dependency.

**Comment by chaoming** [comment]
This issue has been fixed.
